VideoKnowledge/Areas/Admin/Controllers/VideoKnowledgesQuestionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using VideoKnowledge.Models;
using VideoKnowledge.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using VideoKnowledge.Models.ViewModels;
using System.Collections.Generic;

namespace VideoKnowledge.Areas.Admin.Controllers
{
    /// <summary>
    /// Gestisce le operazioni CRUD (Create, Read, Update, Delete) relative alle domande dei quiz associati a eventi di conoscenza video.
    /// Comprende anche la visualizzazione dei risultati dei quiz completati dagli utenti.
    /// Accessibile agli utenti autenticati e autorizzati.
    /// </summary>
    [Area("Admin")]
    [Authorize]
    public class VideoKnowledgesQuestionsController : Controller
    {
        private readonly DataContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public VideoKnowledgesQuestionsController(DataContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        /// <summary>
        /// Visualizza i risultati dei quiz completati dall'utente corrente.
        /// Recupera i quiz completati, i relativi eventi e contenuti video, e li associa in un ViewModel.
        /// </summary>
        /// <returns>Vista contenente i risultati dei quiz completati.</returns>
        public async Task<IActionResult> UserQuizResults()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            // Ottieni tutti i quiz completati dall'utente
            var completedQuizzes = await _context.UserTestResults
                .Where(utr => utr.UserId == userId)
                .ToListAsync();

            // Estrai tutti gli ID di VideoKnowledgeEvents dai quiz completati
            var videoEventIds = completedQuizzes.Select(q => q.VidEventId).ToList();

            // Ottieni tutti i VideoKnowledgeEvents corrispondenti
            var videoEvents = await _context.VideoKnowledgeEvents
                .Where(ve => videoEventIds.Contains(ve.Id))
                .ToListAsync();

            // Estrai tutti gli ID di VideoKnowledgeContents associati ai VideoKnowledgeEvents
            var videoContentIds = videoEvents.Select(ve => ve.VidKnowLinkedId).ToList();

            // Ottieni tutti i VideoKnowledgeContents corrispondenti
            var videoContents = await _context.VideoKnowledgeContents
                .Where(vc => videoContentIds.Contains(vc.Id))
                .Include(vkc => vkc.Category) // Include la categoria per visualizzarla nella vista
                .ToListAsync();

            // Creazione di un dizionario per mappare VideoEventId a VidKnowId e EvntQuizName
            var eventToContentMap = videoEvents.ToDictionary(ve => ve.Id, ve => new { ve.VidKnowLinkedId, ve.EvntQuizName });

            // Assegnazione di VidKnowId e Name a ogni UserTestResults
            foreach (var quiz in completedQuizzes)
            {
                if (eventToContentMap.ContainsKey(quiz.VidEventId))
                {
                    quiz.VidKnowId = eventToContentMap[quiz.VidEventId].VidKnowLinkedId;
                    quiz.Name = eventToContentMap[quiz.VidEventId].EvntQuizName;
                }
            }

            // Crea il ViewModel con i dati ottenuti
            var viewModel = new UserCompletedQuizzesViewModel
            {
                VideoKnowledgeContents = videoContents,
                UserTestResults = completedQuizzes
            };

            return View(viewModel);
        }

        /// <summary>
        /// Mostra l'elenco delle domande di un evento quiz specifico.
        /// Permette il filtraggio per un evento selezionato.
        /// </summary>
        /// <param name="SelectedEvent">ID dell'evento selezionato per filtrare le domande.</param>
        /// <returns>Vista con l'elenco delle domande associate all'evento specifico.</returns>
        public ActionResult Index(int? SelectedEvent)
        {
            var eventContainer = _context.VideoKnowledgeEvents.OrderBy(q => q.EvntQuizName).ToList();
            ViewBag.SelectedVideoKnowledgeContent = new SelectList(eventContainer, "videoKnowledgeContentId", "Name", SelectedEvent);
            int vdkEventId = SelectedEvent.GetValueOrDefault();

            IQueryable<Question> VideoKnowledgeEvents = _context.Questions
                .Where(c => !SelectedEvent.HasValue || c.EventId == vdkEventId)
                .OrderBy(d => d.Id)
                .Include(d => d.Evnt);
            var sql = VideoKnowledgeEvents.ToString();
            return View(VideoKnowledgeEvents.ToList());
        }

        /// <summary>
        /// Mostra l'interfaccia per giocare un quiz associato a un evento video.
        /// Recupera le domande del quiz e il contenuto video correlato.
        /// </summary>
        /// <param name="id">ID dell'evento del quiz.</param>
        /// <returns>Vista con i dettagli del quiz e le sue domande.</returns>
        public async Task<IActionResult> QuizPlayer(long id)
        {
            // Carica l'evento del quiz con le domande associate
            var vidknowEvnt = await _context.VideoKnowledgeEvents
                .Include(e => e.QuestionList)
                .Include(e => e.VidKnowLinked) // Include il contenuto del video associato
                .FirstOrDefaultAsync(e => e.Id == id);

            if (vidknowEvnt == null)
            {
                return NotFound();
            }

            // Inizializza SelectedAnswer a null per tutte le domande
            foreach (var question in vidknowEvnt.QuestionList)
            {
                question.SelectedAnswer = null; // Imposta SelectedAnswer a null per ogni domanda
            }

            return View(vidknowEvnt);
        }

        /// <summary>
        /// Elabora le risposte inviate da un utente per un quiz specifico.
        /// Calcola il punteggio, determina il risultato (superato o fallito), e salva i dati nel database.
        /// </summary>
        /// <param name="model">Dati del quiz con le risposte dell'utente.</param>
        /// <param name="evntId">ID dell'evento del quiz.</param>
        /// <returns>
        /// Un oggetto JSON contenente il risultato del quiz e il numero di risposte corrette e totali.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> SubmitQuizAsync(VideoKnowledgeEvent model, long evntId)
        {
            if (model.QuestionList == null || !model.QuestionList.Any())
            {
                return Json(new { success = false, message = "Non ci sono domande nel quiz." });
            }

            // Calcolo delle risposte corrette
            int correctAnswers = 0;
            int totalQuestions = model.QuestionList.Count;

            foreach (var question in model.QuestionList)
            {
                var storedQuestion = _context.Questions.FirstOrDefault(q => q.Id == question.Id);
                if (storedQuestion != null && question.SelectedAnswer == storedQuestion.CorrectAnswer)
                {
                    correctAnswers++;
                }
            }

            // Recupero dell'ID utente corrente
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            // Verifica se esiste già un risultato del quiz per lo stesso evento e utente
            var existingResult = _context.UserTestResults
                .FirstOrDefault(utr => utr.VidEventId == evntId && utr.UserId == userId);

            if (existingResult != null)
            {
                // Se esiste, elimina il risultato precedente
                _context.UserTestResults.Remove(existingResult);
            }

            // Crea un nuovo risultato del quiz
            UserTestResults usrQuizResult = new UserTestResults
            {
                VidEventId = evntId,
                UserId = userId,
                Name = model.Name,
                QuestionsResult = $"Correct Answer: {correctAnswers} on {totalQuestions}, total questions",
                QuizResult = (totalQuestions / 2) < correctAnswers ? "Passed" : "Failed"
            };

            // Aggiungi il nuovo risultato del quiz al contesto
            _context.UserTestResults.Add(usrQuizResult);

            // Salva le modifiche nel database
            await _context.SaveChangesAsync();

            // Restituisce i risultati come JSON
            return Json(new { success = true, totalQuestions, correctAnswers });
        }

        /// <summary>
        /// Fornisce la vista per creare una nuova domanda associata a un evento quiz.
        /// </summary>
        /// <returns>Vista per creare una nuova domanda.</returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Aggiunge una nuova domanda a un evento quiz esistente.
        /// Aggiorna la lista di domande associata all'evento e salva i dati nel database.
        /// </summary>
        /// <param name="vidEvntQuizQuestion">Dati della domanda da aggiungere.</param>
        /// <param name="Id">ID dell'evento quiz associato.</param>
        /// <returns>
        /// In caso di successo, reindirizza alla pagina di modifica dell'evento quiz.
        /// In caso di errore, restituisce la vista con i messaggi di errore.
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Question vidEvntQuizQuestion, long Id)
        {
            if (ModelState.IsValid)
            {

VideoKnowledge/Controllers/VideoKnowledgesContentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VideoKnowledge.Infrastructure;
using VideoKnowledge.Models;

namespace VideoKnowledge.Controllers
{
    /// <summary>
    /// Gestisce le operazioni per visualizzare e cercare contenuti di tipo <see cref="VideoKnowledgeContent"/>.
    /// Include funzionalità per la paginazione e la ricerca.
    /// </summary>
    public class VideoKnowledgesContentsController : Controller
    {
        private readonly DataContext _context;

        /// <summary>
        /// Inizializza una nuova istanza di <see cref="VideoKnowledgesContentsController"/> con il contesto dati specificato.
        /// </summary>
        /// <param name="context">Istanza del contesto dati per accedere al database.</param>
        public VideoKnowledgesContentsController(DataContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Mostra una lista di contenuti con supporto alla paginazione e alla visualizzazione per categoria.
        /// </summary>
        /// <param name="categorySlug">
        /// Lo slug della categoria per filtrare i contenuti.
        /// Se vuoto, vengono mostrati tutti i contenuti.
        /// </param>
        /// <param name="p">Il numero della pagina da visualizzare (predefinito: 1).</param>
        /// <returns>
        /// Una vista con una lista paginata di contenuti. Se la categoria non esiste, reindirizza alla vista principale.
        /// </returns>
        public async Task<IActionResult> Index(string categorySlug = "", int p = 1)
        {
                int pageSize = 8;
                ViewBag.PageNumber = p;
                ViewBag.PageRange = pageSize;
                ViewBag.CategorySlug = categorySlug;

                if (categorySlug == "")
                {
                        //ViewBag.TotalPages = (int)Math.Ceiling((decimal)_context.Products.Count() / pageSize);
                        ViewBag.TotalPages = (int)Math.Ceiling((decimal)_context.VideoKnowledgeContents.Count() / pageSize);

                        //return View(await _context.Products.OrderByDescending(p => p.Id).Skip((p - 1) * pageSize).Take(pageSize).ToListAsync());
                        return View(await _context.VideoKnowledgeContents.OrderByDescending(p => p.Id).Skip((p - 1) * pageSize).Take(pageSize).ToListAsync());
                }

                Category category = await _context.Categories.Where(c => c.Slug == categorySlug).FirstOrDefaultAsync();
                if (category == null) return RedirectToAction("Index");

                //var productsByCategory = _context.Products.Where(p => p.CategoryId == category.Id);
                var productsByCategory = _context.VideoKnowledgeContents.Where(p => p.CategoryId == category.Id);
                ViewBag.TotalPages = (int)Math.Ceiling((decimal)productsByCategory.Count() / pageSize);

                return View(await productsByCategory.OrderByDescending(p => p.Id).Skip((p - 1) * pageSize).Take(pageSize).ToListAsync());
        }

        /// <summary>
        /// Cerca contenuti basandosi su un termine di ricerca specificato.
        /// </summary>
        /// <param name="query">Il termine di ricerca da utilizzare per trovare i contenuti.</param>
        /// <returns>
        /// Una vista con una lista di risultati che corrispondono al termine di ricerca nei campi *Name*, *Description* o *Category*.
        /// </returns>
        [HttpGet]
        public IActionResult ContentsSearch(string query)
        {
            var results = _context.VideoKnowledgeContents
                .Where(v => v.Name.Contains(query) || v.Description.Contains(query) || v.Category.Name.Contains(query))
                .ToList();

            return View(results);
        }

    }
}

VideoKnowledge/Areas/Admin/Views/VideoKnowledgesQuestions/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model VideoKnowledge.Models.Question

@{
        ViewData["Title"] = "Create Question";
}

<div class="text-center">
    <h1 class="display-4">Create Question</h1>
</div>
<h1></h1>

<div class="row">
@* <form asp-action="Create" enctype="multipart/form-data"> *@
    <br />
    <br />
   @*  <div id="questionSection" class="container"> *@
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <form asp-action="Create" enctype="multipart/form-data">
                <div class="border container bg-light" style="padding:30px; border-radius:20px;">
                    <div id="question">
                        <div class="form-group row">
                            <div class="col-2">
                                <label>Question : </label>    
                            </div>
                            <div class="col-10">
                                <input class="form-control" asp-for="QuestionText" />
                                <span asp-validation-for="QuestionText" class="text-danger"></span>
                            </div>
                        </div>
                        <br /><br />
                        <div class="form-group row">
                            <div class="col-1"></div>
                            <div class="col-1" style="text-align:right">
                                <label>A) </label>
                            </div>
                            <div class="col-4">
                                <input class="form-control" asp-for="AnswerA" />
                                <span asp-validation-for="AnswerA" class="text-danger"></span>
                            </div>
                            <div class="col-1"></div>
                            <div class="col-1" style="text-align:right">
                                <label>B) </label>
                            </div>
                            <div class="col-4">
                                <input class="form-control" asp-for="AnswerB" />
                                <span asp-validation-for="AnswerB" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-1"></div>
                            <div class="col-1" style="text-align:right">
                                <label>C) </label>
                            </div>
                            <div class="col-4">
                                <input class="form-control" asp-for="AnswerC" />
                                <span asp-validation-for="AnswerC" class="text-danger"></span>
                            </div>
                            <div class="col-1"></div>
                            <div class="col-1" style="text-align:right">
                                <label>D) </label>
                            </div>
                            <div class="col-4">
                                <input class="form-control" asp-for="AnswerD" />
                                <span asp-validation-for="AnswerD" class="text-danger"></span>
                            </div>
                        </div>
                        <br /><br />
                        <div class="form-group row">
                            <div class="col-3 offset-5" style="text-align:right">
                                <label>Select the correct answer: </label>
                            </div>

                            <div class="col-4">
                                @Html.DropDownListFor(m => m.CorrectAnswer,
                                                        new SelectList(new List<string> { "A", "B", "C", "D" }),
                                                        "-- Correct Answer --",
                                                        new { @class = "form-control" })
                            </div>
                        </div>
                            <div class="form-group">
        <br />
        <button class="btn btn-success">Create</button>
        <a href="javascript:history.go(-1)" class="btn btn-secondary">Back to Video Knowledge</a>

    </div>
                    </div>
                </div>

                <br /><br /><br />
            @* } *@
            </form>
 @*         } *@
        <br />
@*         <div>
            <a href="javascript:history.go(-1)">Back to VideoKnowledge</a>
        </div> *@
    @* </div> *@
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/Quiz.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
}

VideoKnowledge/Areas/Admin/Views/VideoKnowledgesQuestions/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model VideoKnowledge.Models.Question
@{
    ViewData["Title"] = "Edit Question";
}
<div class="text-center">
    <h1 class="display-4">Edit Question</h1>
</div>
<h1></h1>

<div class="row">
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <form asp-action="Edit" enctype="multipart/form-data">
        <div class="border container bg-light" style="padding:30px; border-radius:20px;">
            <div id="question">
                <div class="form-group row">
                    <div class="col-2">
                        <label>Question : </label>
                    </div>
                    <div class="col-10">
                        <input class="form-control" asp-for="QuestionText" />
                        <span asp-validation-for="QuestionText" class="text-danger"></span>
                    </div>    
                </div>
                <br /><br />
                <div class="form-group row">
                    <div class="col-1"></div>
                    <div class="col-1" style="text-align:right">
                        <label>A) </label>    
                    </div>
                    <div class="col-4">
                        <input class="form-control" asp-for="AnswerA" />
                        <span asp-validation-for="AnswerA" class="text-danger"></span>
                    </div>
                    <div class="col-1"></div>
                    <div class="col-1" style="text-align:right">
                        <label>B) </label>
                    </div>
                    <div class="col-4">
                        <input class="form-control" asp-for="AnswerB" />
                        <span asp-validation-for="AnswerB" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-1"></div>
                    <div class="col-1" style="text-align:right">
                                <label>C) </label>
                    </div>
                    <div class="col-4">
                        <input class="form-control" asp-for="AnswerC" />
                        <span asp-validation-for="AnswerC" class="text-danger"></span>
                    </div>
                    <div class="col-1"></div>
                    <div class="col-1" style="text-align:right">
                        <label>D) </label>
                    </div>
                    <div class="col-4">
                        <input class="form-control" asp-for="AnswerD" />
                        <span asp-validation-for="AnswerD" class="text-danger"></span>
                    </div>
                </div>
                <br /><br />
                <div class="form-group row">
                    <div class="col-3 offset-5" style="text-align:right">
                        <label>Select the correct answer: </label>
                    </div>

                    <div class="col-4">
                        @Html.DropDownListFor(m => m.CorrectAnswer,
                                                new SelectList(new List<string> { "A", "B", "C", "D" }),
                                                "-- Correct Answer --",
                                                new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <br />
                    <button class="btn btn-warning btn-sm">Edit</button>
                    <a href="javascript:history.go(-1)" class="btn btn-secondary">Back to Video Knowledge</a>
                </div>    
            </div>    
        </div>
        <br /><br /><br />
    </form>
    
</div>
           

VideoKnowledge/Areas/Admin/Views/VideoKnowledgesQuestions/Index.cshtml
@*
    Per più informazioni sull'abilitazione di MVC per progetti vuoti, visitare https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Video Knowledge Questions";
}

<h2>Video Knowledge Questions</h2>

<form asp-action="Index">
    <div class="form-group">
        <label for="SelectedEvent">Select Event</label>
        @Html.DropDownList("SelectedEvent", (SelectList)ViewBag.SelectedVideoKnowledgeContent, "Select an Event", new { @class = "form-control", @onchange = "this.form.submit();" })
    </div>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Question ID</th>
            <th>Question Text</th>
            <th>Event Name</th>
            <th>Quiz Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-event-id="@item.EventId">
                <td>@item.Id</td>
                <td>@item.QuestionText</td>
                <td>@item.Evnt.EvntQuizName</td>
                <td class="quiz-name">Loading...</td> <!-- Qui verrà visualizzato il Quiz Name -->
                <td>
                    <a href="@Url.Action("QuizPlayer", "VideoKnowledgesQuestions", new { id = item.EventId })" class="btn btn-primary">Vai al Quiz</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Script per recuperare il nome del quiz e aggiornare la vista -->
<script>
    $(document).ready(function () {
        // Scorri tutte le righe della tabella per recuperare l'ID dell'evento
        $('tr[data-event-id]').each(function () {
            var row = $(this);
            var eventId = row.data('event-id');

            // Chiamata AJAX per ottenere il nome del quiz
            $.ajax({
                url: '/api/Event/GetQuizName', // Assicurati che l'URL corrisponda all'endpoint del tuo controller
                type: 'GET',
                data: { eventId: eventId },
                success: function (result) {
                    // Aggiorna la cella con il nome del quiz restituito
                    row.find('.quiz-name').text(result);
                },
                error: function () {
                    // In caso di errore, imposta un testo di default
                    row.find('.quiz-name').text('N/A');
                }
            });
        });
    });
</script>

VideoKnowledge/Areas/Admin/Views/VideoKnowledgesQuestions/QuizPlayer.cshtml
@model VideoKnowledge.Models.VideoKnowledgeEvent

@{
    ViewData["Title"] = "Quiz Player";
}

<div class="text-center">
    <h1 class="display-4">Play Quiz</h1>
</div>

<div class="container">
    <div id="timer" class="timer"></div>
    <div id="questionSection">
        <form id="quizForm" asp-action="SubmitQuiz" asp-controller="VideoKnowledgesQuestions" method="post">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>

            <input type="hidden" name="EventId" value="@Model.Id" />

            @if (Model.QuestionList != null && Model.QuestionList.Any())
            {
                var questionList = Model.QuestionList.ToList();
                for (int i = 0; i < questionList.Count; i++)
                {
                    var question = questionList[i];
                    <div class="border bg-light p-4 mb-4">
                        <div class="form-group row">
                            <div class="col-12">
                                <label>@question.QuestionText</label>
                            </div>
                        </div>
                        <br />
                        <div class="form-group row">
                            <div class="col-6">
                                <input type="radio" name="QuestionList[@i].SelectedAnswer" value="A" />
                                <label>@question.AnswerA</label>
                            </div>
                            <div class="col-6">
                                <input type="radio" name="QuestionList[@i].SelectedAnswer" value="B" />
                                <label>@question.AnswerB</label>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-6">
                                <input type="radio" name="QuestionList[@i].SelectedAnswer" value="C" />
                                <label>@question.AnswerC</label>
                            </div>
                            <div class="col-6">
                                <input type="radio" name="QuestionList[@i].SelectedAnswer" value="D" />
                                <label>@question.AnswerD</label>
                            </div>
                        </div>

                        <input type="hidden" name="QuestionList[@i].Id" value="@question.Id" />

                        <hr />
                    </div>
                }
            }

            <div class="form-group">
                <a href="javascript:history.go(-1)" class="btn btn-secondary">Get It</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        // Timer duration in seconds
        var timerDuration = @Model.EvntTimerDuration;


        // Function to start the countdown timer
        function startTimer(duration, display) {
            var timer = duration, minutes, seconds;
            var interval = setInterval(function () {
                minutes = parseInt(timer / 60, 10);
                seconds = parseInt(timer % 60, 10);

                minutes = minutes < 10 ? "0" + minutes : minutes;
                seconds = seconds < 10 ? "0" + seconds : seconds;

                display.textContent = minutes + ":" + seconds;

                if (--timer < 0) {
                    clearInterval(interval);
                    submitQuiz();
                }
            }, 1000);
        }

        window.onload = function () {
            var display = document.querySelector('#timer');
            startTimer(timerDuration, display);
        };
    </script>
}

<style>
    .timer {
        position: fixed;
        top: 10px;
        right: 10px;
        background-color: #007bff;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        font-size: 1.5rem;
        font-weight: bold;
        z-index: 1000;
    }
</style>

VideoKnowledge/Areas/Admin/Views/VideoKnowledgesQuestions/UserQuizResults.cshtml
@model UserCompletedQuizzesViewModel

@{
    ViewData["Title"] = "Completed Quizzes";
}

<h1>Completed Quizzes</h1>

<table class="table">
    <thead>
        <tr>
            <th>Video Name</th>
            <th>Cover</th>
            <th>Quiz Name</th>
            <th>Quiz Result</th>
            <th>Correct Answers</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var quizResult in Model.UserTestResults)
        {
            var videoContent = Model.VideoKnowledgeContents.FirstOrDefault(vkc => vkc.Id == quizResult.VidKnowId);
            <tr>
                <td>
                    @videoContent?.Name
                </td>
                <td>
                    @* definizione path su cui leggere le immagini *@
                    <img src="/media/imagesOfKnowledges/@videoContent.Image" width="200" height="200" alt="" />
                </td>
                <td>
                    @quizResult.Name
                </td>
                <td>
                    @quizResult.QuizResult
                </td>
                <td>
                    @quizResult.QuestionsResult
                </td>
                <td>
                    <a class="btn btn-addList" asp-area="Admin" asp-controller="VideoKnowledgesContents" asp-action="Player" asp-route-id="@quizResult.VidKnowId">Replay</a>
                </td>
            </tr>
        }
    </tbody>
</table>